apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: ywc17-api
type: Opaque
data:
  mongourl: bW9uZ29kYjovL3l3YzE3OmppR0FyY3FtNGpDUkhHbUZxSkdQMlJAbG9jYWxob3N0OjI3MDE3L3l3YzE3LXByb2QK
  jwtsecret: WXdjMTVXZUFyZUFsd2F5c0hpcmluZwo=